# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XSSAlert/ui/main.ui'
#
# Created: Mon May 23 17:31:13 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_XSS_ALERT(object):
    def setupUi(self, XSS_ALERT):
        XSS_ALERT.setObjectName(_fromUtf8("XSS_ALERT"))
        XSS_ALERT.setWindowModality(QtCore.Qt.ApplicationModal)
        XSS_ALERT.setEnabled(True)
        XSS_ALERT.resize(878, 568)
        XSS_ALERT.setMouseTracking(False)
        XSS_ALERT.setFocusPolicy(QtCore.Qt.TabFocus)
        XSS_ALERT.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        XSS_ALERT.setWindowIcon(icon)
        XSS_ALERT.setAutoFillBackground(False)
        XSS_ALERT.setStyleSheet(_fromUtf8(""))
        XSS_ALERT.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        XSS_ALERT.setDocumentMode(False)
        XSS_ALERT.setTabShape(QtGui.QTabWidget.Triangular)
        XSS_ALERT.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        XSS_ALERT.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(XSS_ALERT)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setCursor(QtCore.Qt.PointingHandCursor)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.URL_Basic = QtGui.QWidget()
        self.URL_Basic.setObjectName(_fromUtf8("URL_Basic"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.URL_Basic)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_5 = QtGui.QFrame(self.URL_Basic)
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.frame_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.url_textbox = QtGui.QLineEdit(self.frame_5)
        self.url_textbox.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";\n"
""))
        self.url_textbox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.url_textbox.setText(_fromUtf8(""))
        self.url_textbox.setFrame(True)
        self.url_textbox.setEchoMode(QtGui.QLineEdit.Normal)
        self.url_textbox.setObjectName(_fromUtf8("url_textbox"))
        self.horizontalLayout_2.addWidget(self.url_textbox)
        self.verticalLayout_15.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.getstring_checkbox = QtGui.QCheckBox(self.frame_5)
        self.getstring_checkbox.setObjectName(_fromUtf8("getstring_checkbox"))
        self.horizontalLayout_3.addWidget(self.getstring_checkbox)
        self.getstring_textbox = QtGui.QLineEdit(self.frame_5)
        self.getstring_textbox.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.getstring_textbox.setText(_fromUtf8(""))
        self.getstring_textbox.setObjectName(_fromUtf8("getstring_textbox"))
        self.horizontalLayout_3.addWidget(self.getstring_textbox)
        self.verticalLayout_15.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.poststring_checkbox = QtGui.QCheckBox(self.frame_5)
        self.poststring_checkbox.setObjectName(_fromUtf8("poststring_checkbox"))
        self.horizontalLayout_9.addWidget(self.poststring_checkbox)
        self.poststring_textbox = QtGui.QLineEdit(self.frame_5)
        self.poststring_textbox.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.poststring_textbox.setObjectName(_fromUtf8("poststring_textbox"))
        self.horizontalLayout_9.addWidget(self.poststring_textbox)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem2)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.xml_checkbox = QtGui.QCheckBox(self.frame_5)
        self.xml_checkbox.setObjectName(_fromUtf8("xml_checkbox"))
        self.horizontalLayout_20.addWidget(self.xml_checkbox)
        self.xml_textbox = QtGui.QLineEdit(self.frame_5)
        self.xml_textbox.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.xml_textbox.setText(_fromUtf8(""))
        self.xml_textbox.setReadOnly(True)
        self.xml_textbox.setObjectName(_fromUtf8("xml_textbox"))
        self.horizontalLayout_20.addWidget(self.xml_textbox)
        self.verticalLayout_15.addLayout(self.horizontalLayout_20)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtGui.QFrame(self.URL_Basic)
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verbose_checkbox = QtGui.QCheckBox(self.frame_6)
        self.verbose_checkbox.setObjectName(_fromUtf8("verbose_checkbox"))
        self.horizontalLayout_26.addWidget(self.verbose_checkbox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.show_fuzz = QtGui.QCheckBox(self.frame_6)
        self.show_fuzz.setObjectName(_fromUtf8("show_fuzz"))
        self.horizontalLayout_26.addWidget(self.show_fuzz)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.full_report = QtGui.QCheckBox(self.frame_6)
        self.full_report.setObjectName(_fromUtf8("full_report"))
        self.horizontalLayout_26.addWidget(self.full_report)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_26)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.hide_frame = QtGui.QFrame(self.URL_Basic)
        self.hide_frame.setFrameShape(QtGui.QFrame.Box)
        self.hide_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.hide_frame.setObjectName(_fromUtf8("hide_frame"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.hide_frame)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem7)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_3 = QtGui.QLabel(self.hide_frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_25.addWidget(self.label_3)
        self.author_name_text = QtGui.QLineEdit(self.hide_frame)
        self.author_name_text.setMaxLength(100)
        self.author_name_text.setObjectName(_fromUtf8("author_name_text"))
        self.horizontalLayout_25.addWidget(self.author_name_text)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem8)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem9)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_4 = QtGui.QLabel(self.hide_frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_27.addWidget(self.label_4)
        self.author_email_text = QtGui.QLineEdit(self.hide_frame)
        self.author_email_text.setMaxLength(200)
        self.author_email_text.setObjectName(_fromUtf8("author_email_text"))
        self.horizontalLayout_27.addWidget(self.author_email_text)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem10)
        self.verticalLayout_20.addLayout(self.horizontalLayout_27)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem11)
        self.verticalLayout_2.addWidget(self.hide_frame)
        self.fuzz_frame = QtGui.QFrame(self.URL_Basic)
        self.fuzz_frame.setFrameShape(QtGui.QFrame.Box)
        self.fuzz_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.fuzz_frame.setObjectName(_fromUtf8("fuzz_frame"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.fuzz_frame)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.DCP_checkBox = QtGui.QCheckBox(self.fuzz_frame)
        self.DCP_checkBox.setObjectName(_fromUtf8("DCP_checkBox"))
        self.verticalLayout_3.addWidget(self.DCP_checkBox)
        self.basicfuzz_checkbox = QtGui.QCheckBox(self.fuzz_frame)
        self.basicfuzz_checkbox.setObjectName(_fromUtf8("basicfuzz_checkbox"))
        self.verticalLayout_3.addWidget(self.basicfuzz_checkbox)
        self.horizontalLayout_24.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.eventfuzz_checkbox = QtGui.QCheckBox(self.fuzz_frame)
        self.eventfuzz_checkbox.setObjectName(_fromUtf8("eventfuzz_checkbox"))
        self.verticalLayout_4.addWidget(self.eventfuzz_checkbox)
        self.charencodefuzz_checkbox = QtGui.QCheckBox(self.fuzz_frame)
        self.charencodefuzz_checkbox.setObjectName(_fromUtf8("charencodefuzz_checkbox"))
        self.verticalLayout_4.addWidget(self.charencodefuzz_checkbox)
        self.horizontalLayout_24.addLayout(self.verticalLayout_4)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.embeddedeventfuzz_checkbox = QtGui.QCheckBox(self.fuzz_frame)
        self.embeddedeventfuzz_checkbox.setObjectName(_fromUtf8("embeddedeventfuzz_checkbox"))
        self.verticalLayout_22.addWidget(self.embeddedeventfuzz_checkbox)
        self.embeddedcharencodefuzz_checkbox = QtGui.QCheckBox(self.fuzz_frame)
        self.embeddedcharencodefuzz_checkbox.setObjectName(_fromUtf8("embeddedcharencodefuzz_checkbox"))
        self.verticalLayout_22.addWidget(self.embeddedcharencodefuzz_checkbox)
        self.horizontalLayout_24.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.regularfuzz_checkbox = QtGui.QCheckBox(self.fuzz_frame)
        self.regularfuzz_checkbox.setObjectName(_fromUtf8("regularfuzz_checkbox"))
        self.verticalLayout_23.addWidget(self.regularfuzz_checkbox)
        self.urlfuzz_checkbox = QtGui.QCheckBox(self.fuzz_frame)
        self.urlfuzz_checkbox.setObjectName(_fromUtf8("urlfuzz_checkbox"))
        self.verticalLayout_23.addWidget(self.urlfuzz_checkbox)
        self.horizontalLayout_24.addLayout(self.verticalLayout_23)
        self.verticalLayout_21.addLayout(self.horizontalLayout_24)
        self.verticalLayout_2.addWidget(self.fuzz_frame)
        self.horizontalLayout_21.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.URL_Basic, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.extrahttpheader_checkbox = QtGui.QCheckBox(self.frame_2)
        self.extrahttpheader_checkbox.setObjectName(_fromUtf8("extrahttpheader_checkbox"))
        self.horizontalLayout_10.addWidget(self.extrahttpheader_checkbox)
        self.extrahttpheader_textbox = QtGui.QLineEdit(self.frame_2)
        self.extrahttpheader_textbox.setText(_fromUtf8(""))
        self.extrahttpheader_textbox.setObjectName(_fromUtf8("extrahttpheader_textbox"))
        self.horizontalLayout_10.addWidget(self.extrahttpheader_textbox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.extrahttpheaderfile_checkbox = QtGui.QCheckBox(self.frame_2)
        self.extrahttpheaderfile_checkbox.setObjectName(_fromUtf8("extrahttpheaderfile_checkbox"))
        self.horizontalLayout_11.addWidget(self.extrahttpheaderfile_checkbox)
        self.extrahttpheaderfile_textbox = QtGui.QLineEdit(self.frame_2)
        self.extrahttpheaderfile_textbox.setText(_fromUtf8(""))
        self.extrahttpheaderfile_textbox.setReadOnly(True)
        self.extrahttpheaderfile_textbox.setObjectName(_fromUtf8("extrahttpheaderfile_textbox"))
        self.horizontalLayout_11.addWidget(self.extrahttpheaderfile_textbox)
        self.extrahttpheaderfile_upload_button = QtGui.QPushButton(self.frame_2)
        self.extrahttpheaderfile_upload_button.setStyleSheet(_fromUtf8(""))
        self.extrahttpheaderfile_upload_button.setObjectName(_fromUtf8("extrahttpheaderfile_upload_button"))
        self.horizontalLayout_11.addWidget(self.extrahttpheaderfile_upload_button)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.default_fakeheader_checkBox = QtGui.QCheckBox(self.frame_2)
        self.default_fakeheader_checkBox.setObjectName(_fromUtf8("default_fakeheader_checkBox"))
        self.verticalLayout_9.addWidget(self.default_fakeheader_checkBox)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem14)
        self.verticalLayout_6.addWidget(self.frame_2)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem15)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.extrapayloadvector_checkbox = QtGui.QCheckBox(self.frame_3)
        self.extrapayloadvector_checkbox.setObjectName(_fromUtf8("extrapayloadvector_checkbox"))
        self.horizontalLayout_17.addWidget(self.extrapayloadvector_checkbox)
        self.extrapayloadvector_textbox = QtGui.QLineEdit(self.frame_3)
        self.extrapayloadvector_textbox.setText(_fromUtf8(""))
        self.extrapayloadvector_textbox.setObjectName(_fromUtf8("extrapayloadvector_textbox"))
        self.horizontalLayout_17.addWidget(self.extrapayloadvector_textbox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem16)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.extrapayloadvectorfile_checkbox = QtGui.QCheckBox(self.frame_3)
        self.extrapayloadvectorfile_checkbox.setObjectName(_fromUtf8("extrapayloadvectorfile_checkbox"))
        self.horizontalLayout_18.addWidget(self.extrapayloadvectorfile_checkbox)
        self.extrapayloadvectorfile_textbox = QtGui.QLineEdit(self.frame_3)
        self.extrapayloadvectorfile_textbox.setText(_fromUtf8(""))
        self.extrapayloadvectorfile_textbox.setReadOnly(True)
        self.extrapayloadvectorfile_textbox.setObjectName(_fromUtf8("extrapayloadvectorfile_textbox"))
        self.horizontalLayout_18.addWidget(self.extrapayloadvectorfile_textbox)
        self.extrapayload_upload_button = QtGui.QPushButton(self.frame_3)
        self.extrapayload_upload_button.setStyleSheet(_fromUtf8(""))
        self.extrapayload_upload_button.setObjectName(_fromUtf8("extrapayload_upload_button"))
        self.horizontalLayout_18.addWidget(self.extrapayload_upload_button)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self.verticalLayout_7.addWidget(self.frame_3)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem18)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_4 = QtGui.QFrame(self.tab_3)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.cookie_checkbox = QtGui.QCheckBox(self.frame_4)
        self.cookie_checkbox.setObjectName(_fromUtf8("cookie_checkbox"))
        self.horizontalLayout_8.addWidget(self.cookie_checkbox)
        self.cookie_textbox = QtGui.QLineEdit(self.frame_4)
        self.cookie_textbox.setStyleSheet(_fromUtf8(""))
        self.cookie_textbox.setText(_fromUtf8(""))
        self.cookie_textbox.setObjectName(_fromUtf8("cookie_textbox"))
        self.horizontalLayout_8.addWidget(self.cookie_textbox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem19)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.referer_checkbox = QtGui.QCheckBox(self.frame_4)
        self.referer_checkbox.setObjectName(_fromUtf8("referer_checkbox"))
        self.horizontalLayout_12.addWidget(self.referer_checkbox)
        self.referer_textbox = QtGui.QLineEdit(self.frame_4)
        self.referer_textbox.setStyleSheet(_fromUtf8(""))
        self.referer_textbox.setText(_fromUtf8(""))
        self.referer_textbox.setObjectName(_fromUtf8("referer_textbox"))
        self.horizontalLayout_12.addWidget(self.referer_textbox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem20)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.timeout_checkbox = QtGui.QCheckBox(self.frame_4)
        self.timeout_checkbox.setObjectName(_fromUtf8("timeout_checkbox"))
        self.horizontalLayout_13.addWidget(self.timeout_checkbox)
        self.timeout_textbox = QtGui.QLineEdit(self.frame_4)
        self.timeout_textbox.setStyleSheet(_fromUtf8(""))
        self.timeout_textbox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.timeout_textbox.setMaxLength(3)
        self.timeout_textbox.setObjectName(_fromUtf8("timeout_textbox"))
        self.horizontalLayout_13.addWidget(self.timeout_textbox)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem21)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.URLencoding_checkbox = QtGui.QCheckBox(self.frame_4)
        self.URLencoding_checkbox.setObjectName(_fromUtf8("URLencoding_checkbox"))
        self.horizontalLayout_16.addWidget(self.URLencoding_checkbox)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem23)
        self.URLencoding_comboBox = QtGui.QComboBox(self.frame_4)
        self.URLencoding_comboBox.setStyleSheet(_fromUtf8(""))
        self.URLencoding_comboBox.setObjectName(_fromUtf8("URLencoding_comboBox"))
        self.URLencoding_comboBox.addItem(_fromUtf8(""))
        self.URLencoding_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.URLencoding_comboBox)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem24)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem25)
        self.verticalLayout_5.addWidget(self.frame_4)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem26)
        self.verticalLayout_13.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.frame_7 = QtGui.QFrame(self.tab_5)
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.create_default_XML = QtGui.QRadioButton(self.frame_7)
        self.create_default_XML.setObjectName(_fromUtf8("create_default_XML"))
        self.verticalLayout_18.addWidget(self.create_default_XML)
        self.delete_default_XML = QtGui.QRadioButton(self.frame_7)
        self.delete_default_XML.setObjectName(_fromUtf8("delete_default_XML"))
        self.verticalLayout_18.addWidget(self.delete_default_XML)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem27)
        self.file_create_alert = QtGui.QLabel(self.frame_7)
        self.file_create_alert.setObjectName(_fromUtf8("file_create_alert"))
        self.verticalLayout_18.addWidget(self.file_create_alert)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_17.addWidget(self.frame_7)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem28)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem29)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem30)
        self.start_button = QtGui.QPushButton(self.frame)
        self.start_button.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";\n"
"\n"
""))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.horizontalLayout_23.addWidget(self.start_button)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem31)
        self.quit_button = QtGui.QPushButton(self.frame)
        self.quit_button.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";\n"
""))
        self.quit_button.setObjectName(_fromUtf8("quit_button"))
        self.horizontalLayout_23.addWidget(self.quit_button)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem32)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.verticalLayout_11.addWidget(self.frame)
        XSS_ALERT.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(XSS_ALERT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        XSS_ALERT.setMenuBar(self.menubar)
        self.actionAbout = QtGui.QAction(XSS_ALERT)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNew = QtGui.QAction(XSS_ALERT)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionNew.setIconVisibleInMenu(True)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionExit = QtGui.QAction(XSS_ALERT)
        self.actionExit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionExit.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionExit.setIconVisibleInMenu(False)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPreferences = QtGui.QAction(XSS_ALERT)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionUpdate = QtGui.QAction(XSS_ALERT)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.menuAbout.addAction(self.actionUpdate)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(XSS_ALERT)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), XSS_ALERT.close)
        QtCore.QObject.connect(self.quit_button, QtCore.SIGNAL(_fromUtf8("pressed()")), XSS_ALERT.close)
        QtCore.QMetaObject.connectSlotsByName(XSS_ALERT)
        XSS_ALERT.setTabOrder(self.tabWidget, self.url_textbox)
        XSS_ALERT.setTabOrder(self.url_textbox, self.getstring_checkbox)
        XSS_ALERT.setTabOrder(self.getstring_checkbox, self.getstring_textbox)
        XSS_ALERT.setTabOrder(self.getstring_textbox, self.poststring_checkbox)
        XSS_ALERT.setTabOrder(self.poststring_checkbox, self.poststring_textbox)
        XSS_ALERT.setTabOrder(self.poststring_textbox, self.xml_checkbox)
        XSS_ALERT.setTabOrder(self.xml_checkbox, self.xml_textbox)
        XSS_ALERT.setTabOrder(self.xml_textbox, self.verbose_checkbox)
        XSS_ALERT.setTabOrder(self.verbose_checkbox, self.show_fuzz)
        XSS_ALERT.setTabOrder(self.show_fuzz, self.full_report)
        XSS_ALERT.setTabOrder(self.full_report, self.author_name_text)
        XSS_ALERT.setTabOrder(self.author_name_text, self.author_email_text)
        XSS_ALERT.setTabOrder(self.author_email_text, self.DCP_checkBox)
        XSS_ALERT.setTabOrder(self.DCP_checkBox, self.basicfuzz_checkbox)
        XSS_ALERT.setTabOrder(self.basicfuzz_checkbox, self.eventfuzz_checkbox)
        XSS_ALERT.setTabOrder(self.eventfuzz_checkbox, self.charencodefuzz_checkbox)
        XSS_ALERT.setTabOrder(self.charencodefuzz_checkbox, self.embeddedeventfuzz_checkbox)
        XSS_ALERT.setTabOrder(self.embeddedeventfuzz_checkbox, self.embeddedcharencodefuzz_checkbox)
        XSS_ALERT.setTabOrder(self.embeddedcharencodefuzz_checkbox, self.regularfuzz_checkbox)
        XSS_ALERT.setTabOrder(self.regularfuzz_checkbox, self.urlfuzz_checkbox)
        XSS_ALERT.setTabOrder(self.urlfuzz_checkbox, self.extrahttpheader_checkbox)
        XSS_ALERT.setTabOrder(self.extrahttpheader_checkbox, self.extrahttpheader_textbox)
        XSS_ALERT.setTabOrder(self.extrahttpheader_textbox, self.extrahttpheaderfile_checkbox)
        XSS_ALERT.setTabOrder(self.extrahttpheaderfile_checkbox, self.extrahttpheaderfile_textbox)
        XSS_ALERT.setTabOrder(self.extrahttpheaderfile_textbox, self.extrahttpheaderfile_upload_button)
        XSS_ALERT.setTabOrder(self.extrahttpheaderfile_upload_button, self.default_fakeheader_checkBox)
        XSS_ALERT.setTabOrder(self.default_fakeheader_checkBox, self.extrapayloadvectorfile_checkbox)
        XSS_ALERT.setTabOrder(self.extrapayloadvectorfile_checkbox, self.extrapayloadvectorfile_textbox)
        XSS_ALERT.setTabOrder(self.extrapayloadvectorfile_textbox, self.extrapayload_upload_button)
        XSS_ALERT.setTabOrder(self.extrapayload_upload_button, self.extrapayloadvector_checkbox)
        XSS_ALERT.setTabOrder(self.extrapayloadvector_checkbox, self.extrapayloadvector_textbox)
        XSS_ALERT.setTabOrder(self.extrapayloadvector_textbox, self.cookie_checkbox)
        XSS_ALERT.setTabOrder(self.cookie_checkbox, self.cookie_textbox)
        XSS_ALERT.setTabOrder(self.cookie_textbox, self.referer_checkbox)
        XSS_ALERT.setTabOrder(self.referer_checkbox, self.referer_textbox)
        XSS_ALERT.setTabOrder(self.referer_textbox, self.timeout_checkbox)
        XSS_ALERT.setTabOrder(self.timeout_checkbox, self.timeout_textbox)
        XSS_ALERT.setTabOrder(self.timeout_textbox, self.URLencoding_checkbox)
        XSS_ALERT.setTabOrder(self.URLencoding_checkbox, self.URLencoding_comboBox)
        XSS_ALERT.setTabOrder(self.URLencoding_comboBox, self.create_default_XML)
        XSS_ALERT.setTabOrder(self.create_default_XML, self.delete_default_XML)
        XSS_ALERT.setTabOrder(self.delete_default_XML, self.start_button)
        XSS_ALERT.setTabOrder(self.start_button, self.quit_button)

    def retranslateUi(self, XSS_ALERT):
        XSS_ALERT.setWindowTitle(QtGui.QApplication.translate("XSS_ALERT", "XSS Alert", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("XSS_ALERT", " URL ", None, QtGui.QApplication.UnicodeUTF8))
        self.url_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "Ex: http://www.google.com", None, QtGui.QApplication.UnicodeUTF8))
        self.getstring_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "HTTP GET String", None, QtGui.QApplication.UnicodeUTF8))
        self.getstring_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "Ex :?name=xss&lname=", None, QtGui.QApplication.UnicodeUTF8))
        self.poststring_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "HTTP POST String", None, QtGui.QApplication.UnicodeUTF8))
        self.poststring_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "Ex:name=xss&lname=", None, QtGui.QApplication.UnicodeUTF8))
        self.xml_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Output XML File", None, QtGui.QApplication.UnicodeUTF8))
        self.xml_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.verbose_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.show_fuzz.setText(QtGui.QApplication.translate("XSS_ALERT", "Fuzz Vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.full_report.setText(QtGui.QApplication.translate("XSS_ALERT", "Generate Full Report", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("XSS_ALERT", "Your Name :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("XSS_ALERT", " Your Email :", None, QtGui.QApplication.UnicodeUTF8))
        self.DCP_checkBox.setText(QtGui.QApplication.translate("XSS_ALERT", " DCP Vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.basicfuzz_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Basic Vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.eventfuzz_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Event Vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.charencodefuzz_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Charactor encode Vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.embeddedeventfuzz_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Embedded Event vector", None, QtGui.QApplication.UnicodeUTF8))
        self.embeddedcharencodefuzz_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Embedded Charactor encode vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.regularfuzz_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Regular HTML vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.urlfuzz_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "URL Obfussion Vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.URL_Basic), QtGui.QApplication.translate("XSS_ALERT", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.extrahttpheader_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Extra Http Header", None, QtGui.QApplication.UnicodeUTF8))
        self.extrahttpheader_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "Ex:Accept: image/gif", None, QtGui.QApplication.UnicodeUTF8))
        self.extrahttpheaderfile_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Extra Http Headers", None, QtGui.QApplication.UnicodeUTF8))
        self.extrahttpheaderfile_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "Valid XML format", None, QtGui.QApplication.UnicodeUTF8))
        self.extrahttpheaderfile_upload_button.setText(QtGui.QApplication.translate("XSS_ALERT", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.default_fakeheader_checkBox.setText(QtGui.QApplication.translate("XSS_ALERT", "Default Fake Header", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("XSS_ALERT", "Http Header", None, QtGui.QApplication.UnicodeUTF8))
        self.extrapayloadvector_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Extra Payload Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.extrapayloadvectorfile_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Extra Payload Vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.extrapayloadvectorfile_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "Valid XML format", None, QtGui.QApplication.UnicodeUTF8))
        self.extrapayload_upload_button.setText(QtGui.QApplication.translate("XSS_ALERT", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("XSS_ALERT", "Payload", None, QtGui.QApplication.UnicodeUTF8))
        self.cookie_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Cookie", None, QtGui.QApplication.UnicodeUTF8))
        self.referer_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Referrer", None, QtGui.QApplication.UnicodeUTF8))
        self.timeout_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.timeout_textbox.setStatusTip(QtGui.QApplication.translate("XSS_ALERT", "Ex: 10", None, QtGui.QApplication.UnicodeUTF8))
        self.URLencoding_checkbox.setText(QtGui.QApplication.translate("XSS_ALERT", "Enable URL shortening", None, QtGui.QApplication.UnicodeUTF8))
        self.URLencoding_comboBox.setItemText(0, QtGui.QApplication.translate("XSS_ALERT", "Bit.ly", None, QtGui.QApplication.UnicodeUTF8))
        self.URLencoding_comboBox.setItemText(1, QtGui.QApplication.translate("XSS_ALERT", "TinyUrl", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("XSS_ALERT", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.create_default_XML.setText(QtGui.QApplication.translate("XSS_ALERT", "Create All Extra XML File", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_default_XML.setText(QtGui.QApplication.translate("XSS_ALERT", "Delete All Extra XML File", None, QtGui.QApplication.UnicodeUTF8))
        self.file_create_alert.setText(QtGui.QApplication.translate("XSS_ALERT", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">    </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("XSS_ALERT", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("XSS_ALERT", "         Validate         ", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_button.setText(QtGui.QApplication.translate("XSS_ALERT", "         Quit         ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("XSS_ALERT", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("XSS_ALERT", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("XSS_ALERT", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("XSS_ALERT", "About XSSAlert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("XSS_ALERT", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("XSS_ALERT", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("XSS_ALERT", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("XSS_ALERT", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("XSS_ALERT", "Preferences..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("XSS_ALERT", "Check For Update", None, QtGui.QApplication.UnicodeUTF8))

import xss_rc
