# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XSSAlert/ui/preferences.ui'
#
# Created: Mon May 23 17:31:14 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName(_fromUtf8("Preferences"))
        Preferences.resize(526, 217)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Preferences.setWindowIcon(icon)
        Preferences.setAutoFillBackground(False)
        Preferences.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        Preferences.setSizeGripEnabled(False)
        Preferences.setModal(False)
        self.horizontalLayout_5 = QtGui.QHBoxLayout(Preferences)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(Preferences)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.UserAgentText = QtGui.QLineEdit(self.frame)
        self.UserAgentText.setObjectName(_fromUtf8("UserAgentText"))
        self.verticalLayout_3.addWidget(self.UserAgentText)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.change_proxy = QtGui.QPushButton(self.frame)
        self.change_proxy.setObjectName(_fromUtf8("change_proxy"))
        self.horizontalLayout_4.addWidget(self.change_proxy)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.default_file_path = QtGui.QLineEdit(self.frame)
        self.default_file_path.setReadOnly(True)
        self.default_file_path.setObjectName(_fromUtf8("default_file_path"))
        self.horizontalLayout.addWidget(self.default_file_path)
        self.change_path_pushButton = QtGui.QPushButton(self.frame)
        self.change_path_pushButton.setObjectName(_fromUtf8("change_path_pushButton"))
        self.horizontalLayout.addWidget(self.change_path_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(Preferences)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.SaveButton = QtGui.QPushButton(self.frame_2)
        self.SaveButton.setObjectName(_fromUtf8("SaveButton"))
        self.verticalLayout_2.addWidget(self.SaveButton)
        self.CancelButton = QtGui.QPushButton(self.frame_2)
        self.CancelButton.setObjectName(_fromUtf8("CancelButton"))
        self.verticalLayout_2.addWidget(self.CancelButton)
        self.ResetButton = QtGui.QPushButton(self.frame_2)
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.verticalLayout_2.addWidget(self.ResetButton)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)

        self.retranslateUi(Preferences)
        QtCore.QObject.connect(self.CancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Preferences.close)
        QtCore.QObject.connect(self.SaveButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Preferences.close)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(QtGui.QApplication.translate("Preferences", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Preferences", "User Agent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Preferences", "Proxy ", None, QtGui.QApplication.UnicodeUTF8))
        self.change_proxy.setText(QtGui.QApplication.translate("Preferences", "Change Proxy Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Preferences", "Default File Path", None, QtGui.QApplication.UnicodeUTF8))
        self.change_path_pushButton.setText(QtGui.QApplication.translate("Preferences", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveButton.setText(QtGui.QApplication.translate("Preferences", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.CancelButton.setText(QtGui.QApplication.translate("Preferences", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetButton.setText(QtGui.QApplication.translate("Preferences", "Reset", None, QtGui.QApplication.UnicodeUTF8))

import xss_rc
